title: Nagesh Vashist
logo: /assets/img/logo.png
description: Nagesh Vashist, AWS Certified Solution Architect Associat, Java Developer.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
